# Generated by Django 5.1.3 on 2025-02-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordrecovery',
            options={'verbose_name': 'Recuperação de Senha', 'verbose_name_plural': 'Recuperações de Senha'},
        ),
        migrations.RenameField(
            model_name='passwordrecovery',
            old_name='expiration_date',
            new_name='expire_at',
        ),
        migrations.AlterField(
            model_name='passwordrecovery',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_recoveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
