# Generated by Django 5.1.3 on 2025-02-20 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0003_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaldeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
