# Generated by Django 5.1.3 on 2025-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0003_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='brand',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('ELO', 'Elo'), ('HIPERCARD', 'Hipercard')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
