# Generated by Django 5.1.3 on 2025-02-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0004_goaldeposit_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttransaction',
            name='type',
        ),
    ]
