# Generated by Django 5.1.3 on 2025-02-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0004_alter_creditcard_brand_delete_brand'),
        ('poupeai', '0004_goaldeposit_created_at'),
    ]

    operations = [
    ]
