# Generated by Django 5.1.3 on 2025-02-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0005_remove_accounttransaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fixed',
        ),
    ]
