# Generated by Django 5.1.3 on 2025-02-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0008_cardtransaction_installment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transaction', to='poupeai.transaction'),
        ),
    ]
