# Generated by Django 5.1.3 on 2025-02-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0011_remove_accounttransaction_payment_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
