# Generated by Django 5.1.3 on 2025-02-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0005_merge_20250220_1015'),
        ('poupeai', '0013_alter_transaction_payment_at'),
    ]

    operations = [
    ]
