# Generated by Django 5.1.3 on 2025-02-22 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0014_merge_20250221_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_due',
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='poupeai.invoice'),
        ),
    ]
