# Generated by Django 5.1.3 on 2025-02-22 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poupeai', '0015_remove_invoice_balance_due_remove_invoice_total_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to='poupeai.invoice'),
        ),
    ]
